services:
  - type: web
    name: alist
    env: docker
    repo: https://github.com/jinfeijie/alist-render.git # optional
    region: singapore
    plan: free
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 5244
      - key: DB_TYPE
        value: sqlite3
      - key: DB_TABLE_PREFIX
        value: alist_
