services:
  # A Docker web service
  - type: web
    name: alist
    env: docker
    repo: https://github.com/jinfeijie/alist-render.git # optional
    region: oregon # optional (defaults to oregon)
    plan: free # optional (defaults to starter)
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 5244
      - key: DB_TYPE
        # value: sqlite3
        sync: false
      - key: DB_TABLE_PREFIX
        # value: alist_
        sync: false
      - key: CDN
        sync: false
